import {
  normalizeSocialPlatform,
  normalizeSocialStatus,
  SOCIAL_PLATFORMS,
  SOCIAL_STATUSES,
  SOCIAL_PLATFORM_FACEBOOK,
  SOCIAL_PLATFORM_INSTAGRAM,
  SOCIAL_PLATFORM_LINKEDIN,
  SOCIAL_PLATFORM_TWITTER,
  SOCIAL_PLATFORM_YOUTUBE,
  SOCIAL_STATUS_DRAFT,
  SOCIAL_STATUS_FAILED,
  SOCIAL_STATUS_PUBLISHED,
  SOCIAL_STATUS_SCHEDULED,
  type SocialPlatform,
  type SocialStatus,
} from "@/types/social";

export {
  SOCIAL_PLATFORMS,
  SOCIAL_STATUSES,
  normalizeSocialPlatform,
  normalizeSocialStatus,
  SOCIAL_PLATFORM_FACEBOOK,
  SOCIAL_PLATFORM_INSTAGRAM,
  SOCIAL_PLATFORM_LINKEDIN,
  SOCIAL_PLATFORM_TWITTER,
  SOCIAL_PLATFORM_YOUTUBE,
  SOCIAL_STATUS_DRAFT,
  SOCIAL_STATUS_FAILED,
  SOCIAL_STATUS_PUBLISHED,
  SOCIAL_STATUS_SCHEDULED,
};

export type { SocialPlatform, SocialStatus };

